// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uabxvcvnenhzznowuiad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhYnh2Y3ZuZW5oenpub3d1aWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTE0MzIsImV4cCI6MjA2MTY4NzQzMn0.p4nBoOP9TBT6dbJxox-EHXkQD5QKoOXaRAXBIQh7P-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);